
-- Создание таблиц в SQLite

CREATE TABLE ST_CURATOR (
   CURATOR_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   CURATOR_NAME TEXT NOT NULL,
   CURATOR_ROLE TEXT NOT NULL,
);

CREATE TABLE ST_GROUP (
   GROUP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   GROUP_NAME TEXT NOT NULL,
   GROUP_CURATOR_ID TEXT NOT NULL,
   GROUP_SPECIALITY TEXT NOT NULL
   FOREIGN KEY (GROUP_CURATOR_ID) REFERENCES ST_CURATOR(CURATOR_ID) ON DELETE CASCADE
);

CREATE TABLE ST_STUDENT (
   STUDENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
   STUDENT_NAME TEXT NOT NULL,
   STUDENT_BIRTH_DATE DATE NOT NULL,
   STUDENT_SEX TEXT,
   STUDENT_GROUP_ID INTEGER NOT NULL,
   STUDENT_EDUCATION_YEAR INTEGER NOT NULL,
   FOREIGN KEY (STUDENT_GROUP_ID) REFERENCES ST_GROUP(GROUP_ID) ON DELETE CASCADE
);

-- Вставка начальных данных в таблицы

INSERT INTO ST_CURATOR (CURATOR_NAME, CURATOR_ROLE) 
VALUES ('Доктор Борменталь', 'Доктор');

INSERT INTO ST_CURATOR (CURATOR_NAME, CURATOR_ROLE) 
VALUES ('Профессор Преображенский', 'Профессор');

INSERT INTO ST_GROUP (GROUP_NAME, GROUP_CURATOR_ID, GROUP_SPECIALITY) 
VALUES ('Первая', 1, 'Создание собачек из человеков');

INSERT INTO ST_GROUP (GROUP_NAME, GROUP_CURATOR_ID, GROUP_SPECIALITY) 
VALUES ('Вторая', 2, 'Создание человеков из собачек');

INSERT INTO ST_STUDENT (STUDENT_NAME, STUDENT_SEX, STUDENT_BIRTH_DATE, STUDENT_GROUP_ID, STUDENT_EDUCATION_YEAR)
VALUES ('Иван Сергеевич Степанов', 'М', '1990-03-20', 1, 2006);

INSERT INTO ST_STUDENT (STUDENT_NAME, STUDENT_SEX, STUDENT_BIRTH_DATE, STUDENT_GROUP_ID, STUDENT_EDUCATION_YEAR)
VALUES ('Наталья Андреевна Чичикова', 'Ж', '1990-06-10', 1, 2006);

INSERT INTO ST_STUDENT (STUDENT_NAME, STUDENT_SEX, STUDENT_BIRTH_DATE, STUDENT_GROUP_ID, STUDENT_EDUCATION_YEAR)
VALUES ('Виктор Сидорович Белов', 'М', '1990-01-10', 1, 2006);

INSERT INTO ST_STUDENT (STUDENT_NAME, STUDENT_SEX, STUDENT_BIRTH_DATE, STUDENT_GROUP_ID, STUDENT_EDUCATION_YEAR)
VALUES ('Петр Викторович Сушкин', 'М', '1991-03-12', 2, 2006);

INSERT INTO ST_STUDENT (STUDENT_NAME, STUDENT_SEX, STUDENT_BIRTH_DATE, STUDENT_GROUP_ID, STUDENT_EDUCATION_YEAR)
VALUES ('Вероника Сергеевна Ковалева', 'Ж', '1991-07-19', 2, 2006);

INSERT INTO ST_STUDENT (STUDENT_NAME, STUDENT_SEX, STUDENT_BIRTH_DATE, STUDENT_GROUP_ID, STUDENT_EDUCATION_YEAR)
VALUES ('Ирина Федоровна Истомина', 'Ж', '1991-04-29', 2, 2006);